In [3]:
import numpy as np

def generatore(n,p):
    '''
    n - number of fermions/antifermions
    p - number of filled sites

    Generates a 2n vector with p filled fermions and p filled antifermions
    '''

    vec = np.zeros(2*n)
    #print(vec)

    fermions = np.random.choice(range(n),p, replace=False)
    #print(fermions)

    antifermions = np.random.choice(range(n),p,replace=False)
    #print(antifermions)

    for i in range(p): 
        vec[2*fermions[i]]=1
        vec[2*antifermions[i]+1]=1
    return vec

In [4]:
n = 6

for i in range(0,n):
    print(generatore(n,i))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
[1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
[1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0.]
[0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
